<?php


namespace Trunkrs\SDK\Enum;

class ReasonCode
{
    const ADDRESS_NOT_FOUND = 'ADDRESS_NOT_FOUND';
    const BUSINESS_CLOSED = 'BUSINESS_CLOSED';
    const RECIPIENT_NOT_AT_HOME = 'RECIPIENT_NOT_AT_HOME';
    const NO_TIME_LEFT_IN_TIMESLOT = 'NO_TIME_LEFT_IN_TIMESLOT';
    const REFUSED_BY_CUSTOMER = 'REFUSED_BY_CUSTOMER';
    const DELIVERY_DAMAGED = 'DELIVERY_DAMAGED';
    const DRIVER_INVOLVED_IN_ACCIDENT = 'DRIVER_INVOLVED_IN_ACCIDENT';
    const BAD_ADDRESS = 'BAD_ADDRESS';
    const EXTREME_WEATHER_CONDITIONS = 'EXTREME_WEATHER_CONDITIONS';
    const PARCEL_MISSING = 'PARCEL_MISSING';
    const DELIVER_ADDRESS_NOT_ACCESSIBLE = 'DELIVER_ADDRESS_NOT_ACCESSIBLE';
}