on: ["push", "pull_request"]

name: Tests & Coveralls

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v1
    - name: Install Dependencies
      uses: php-actions/composer@v1
    - name: Run Tests
      uses: php-actions/phpunit@v1
    - name: Upload coverage
      uses: coverallsapp/github-action@v1.0.1

