on: [push, pull_request]

name: CI

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Set-up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        coverage: xdebug
        extensions: mbstring, simplexml, json, spl, pcre, curl
        tools: composer, phpunit:6.5.2

    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: composer install --prefer-dist
      
    - name: Run tests
      env:
        INTEGRATION_API_KEY: ${{ secrets.INTEGRATION_API_KEY }}
      run: |
        phpunit --configuration ./phpunit.dist.xml
        
    - name: Upload coverage
      env:
        COVERALLS_SERVICE_NAME: Github
        COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        php vendor/bin/coveralls coverage/clover.xml

