on: [push, pull_request]

name: CI

jobs:
  test:
    runs-on: ubuntu-latest
    container: phpunit/phpunit:6.5.2
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Install Dependencies
      uses: php-actions/composer@v1
    - name: Run tests
      run: |
        phpunit --configuration ./phpunit.dist.xml
    - name: Upload coverage
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        apk add --no-cache php7-simplexml
        composer global require cedx/coveralls
        coveralls

