on: [push, pull_request]

name: CI

jobs:
  test:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['7.1', '7.2', '7.3', '7.4']
    steps:
    - name: Set-up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        coverage: xdebug
        extensions: mbstring, simplexml, json, spl, pcre, curl
        tools: composer, phpunit:6.5.2

    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: composer install --prefer-dist
      
    - name: Run tests
      run: |
        phpunit --configuration ./phpunit.dist.xml
        
    - name: Upload coverage
      if: matrix.php-versions == '7.4'
      env:
        COVERALLS_SERVICE_NAME: Github
        COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        php vendor/bin/coveralls coverage/clover.xml

